<?php

namespace Foongon\ChallengeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryGamesChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryGamesChallengeRepository extends EntityRepository
{
}
