<?php

namespace Foongon\ChallengeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GamesChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesChallengeRepository extends EntityRepository
{
}
